version: '3'

services:
  FlinkJobManager:
    image: kinghtdom/hadoop3.3-flink1.15
    container_name: FlinkJobManager
    hostname: master
    expose:
      - '6123'
      - '9000'
      - '22'
    ports:
      - '8081:8081' # Flink的WEB UI接口
      - '8088:8088' # Hadoop.Yarn的WEB UI接口
      - '8042:8042' # Hadoop.NodeManager的http服务端口
      - '9870:9870' # Hadoop.NameNode的http服务端口
      - '19888:19888' # Hadoop.jobhistory WEB UI接口
      - '8022:22' # ssh接口
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: FlinkJobManager
    volumes:
      - ..:/www
    networks:
      bigdata:
        ipv4_address: 172.18.0.2

  FlinkTaskManager-1:
    image: kinghtdom/hadoop3.3-flink1.15
    container_name: FlinkTaskManager1
    hostname: worker1
    expose:
      - '6121'
      - '6122'
      - '22'
    depends_on:
      - FlinkJobManager
    command: taskmanager
    links:
      - 'FlinkJobManager:jobmanager'
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: FlinkJobManager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ..:/www
    networks:
      bigdata:
        ipv4_address: 172.18.0.3

  FlinkTaskManager-2:
    image: kinghtdom/hadoop3.3-flink1.15
    container_name: FlinkTaskManager2
    hostname: worker2
    expose:
      - '6121'
      - '6122'
      - '22'
    depends_on:
      - FlinkJobManager
    command: taskmanager
    links:
      - 'FlinkJobManager:jobmanager'
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: FlinkJobManager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ..:/www
    networks:
      bigdata:
        ipv4_address: 172.18.0.4

networks:
  bigdata:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16