version: '3'

services:
  FlinkJobManager:
    image: kinghtdom/hadoop3.3-flink1.15
    container_name: FlinkJobManager
    hostname: master
    expose:
      - '6123'
      - '9000'
      - '22'
    ports:
      - '8081:8081' # Flink的WEB UI接口
      - '8088:8088' # Hadoop.Yarn的WEB UI接口
      - '8042:8042' # Hadoop.NodeManager的http服务端口
      - '9870:9870' # Hadoop.NameNode的http服务端口
      - '19888:19888' # Hadoop.jobhistory WEB UI接口
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: master
    volumes:
      - ..:/www
    networks:
      bigdata:
        ipv4_address: 172.18.0.2

  FlinkTaskManager-1:
    image: kinghtdom/hadoop3.3-flink1.15
    container_name: FlinkTaskManager1
    hostname: worker1
    expose:
      - '6121'
      - '6122'
      - '22'
    depends_on:
      - FlinkJobManager
    command: taskmanager
    links:
      - 'FlinkJobManager:jobmanager'
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: master
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ..:/www
    networks:
      bigdata:
        ipv4_address: 172.18.0.3

  FlinkTaskManager-2:
    image: kinghtdom/hadoop3.3-flink1.15
    container_name: FlinkTaskManager2
    hostname: worker2
    expose:
      - '6121'
      - '6122'
      - '22'
    depends_on:
      - FlinkJobManager
    command: taskmanager
    links:
      - 'FlinkJobManager:jobmanager'
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: master
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ..:/www
    networks:
      bigdata:
        ipv4_address: 172.18.0.4

  ZooKeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: ZooKeeper
    hostname: zookeeper
    expose:
    - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      bigdata:
        ipv4_address: 172.18.0.5

  Kafka:
    image: bitnami/kafka:3.3.1
    container_name: Kafka
    hostname: kafka
    ports:
    - '9092:9092'
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
    networks:
      bigdata:
        ipv4_address: 172.18.0.6

networks:
  bigdata:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16